### ISSUE TITLE
Sometimes A2 will not delete the original command

### ISSUE THREAD

**Issue by n0t0ri0us** [fiskenslakt/A2#3]
I'm using mobile and after I issue $echo it won't delete the original message with the command, I don't know if it's supposed to do that but I believe you smarter people said it should.

**Comment by n0t0ri0us** [comment]
Never mind it seems it just takes some time for it to get rid of it, sorry!

**Comment by fiskenslakt** [comment]
This has to do with discord's latency, and not the bot itself.
