### ISSUE TITLE
Example Config is Tracked but Also Ignored

### ISSUE THREAD

**Issue by MarkKoz** [fiskenslakt/A2#5]
The pattern `*config.json` is too broad and catches `example_config.json`. One solution is to make the pattern more specific. However, I think the example config's place is at the wiki and it shouldn't be committed at all.

**Comment by MajorDisarray** [comment]
We had a discussion about not having the example config and I agree with you. The pattern was written before Fisk commited the example_config. I'm gonna move it to wiki.
